### ISSUE TITLE
scroll-target id lookup fails

### ISSUE THREAD

**Issue by davidgiven** [PolymerElements/iron-scroll-target-behavior#10]
I have a DOM tree which is, roughly:

```
<x-component>
  <iron-pages>
     <div id="foo">
        <x-scrollable scroll-target="foo">
```

x-scrollable has IronScrollTargetBehavior attached. The lookup of 'foo' fails and I end up with null in the scroll-target property.

Going through the code I see this:

```
      var ownerRoot = Polymer.dom(this).getOwnerRoot();
      this.scrollTarget = (ownerRoot && ownerRoot.$) ?
          ownerRoot.$[scrollTarget] : Polymer.dom(this.ownerDocument).querySelector('#' + scrollTarget);
```

ownerRoot is ending up being a documentFragment which has no $ property. Thus, the conditional in the next line is failing. Looking at the contents of the documentFragment, it seems to represent the x-component node of the DOM tree.

Switching from shady DOM to shadow DOM doesn't have any effect.

Any suggestions?

**Comment by blasten** [comment]
@davidgiven This seems odd. Could you provide a jsbin?

**Comment by davidgiven** [comment]
Well, I had a go --- but jsbin doesn't seem to work with Polymer 1.0; I tried with plnkr too, and failed there as well. I just end up in a maze of CORS errors whenever I try to import everything.

(jsbin itself natviely supports only Polymer 0.3.)

Can you point me at a JS snippets service which supports Polymer 1.0?

**Comment by blasten** [comment]
you can use this one: http://jsbin.com/wipiku/edit?html,output

**Comment by pandrese** [comment]
I experience the same error using iron-list. As can be seen in: [http://jsbin.com/xegipuduku/edit?html,console,output]

If I force the assignment of this.scrollTarget, as shown below:

``` javascript
var ownerRoot = Polymer.dom(this).getOwnerRoot();
this.scrollTarget = (ownerRoot && ownerRoot.$) ?
      ownerRoot.$[scrollTarget] : Polymer.dom(this.ownerDocument).querySelector('#' + scrollTarget);
this.scrollTarget = Polymer.dom(ownerRoot).querySelector('#' + scrollTarget);
```

My example renders correctly.

**Comment by frankiefu** [comment]
@blasten  I think you need to get the `host` of the `root` in order to access `$`.  e.g. `ownerRoot.host.$[scrollTarget]`
