### ISSUE TITLE
Polymer 2.0 usage?

### ISSUE THREAD

**Issue by daKmoR** [PolymerElements/iron-scroll-target-behavior#28]
hey,
I was just wondering but this element is currently not suited to be used by an "full" Polymer 2 Project right? as behaviors are no longer available... 
something like 
`class MenusSticky extends IronScrollBehavior(Polymer.Element) {`
would be nice - but not yet possible as far as I can see...

just wanna be sure before hacking something together myself :p

**Comment by blasten** [comment]
We will. For now the focus is hybrid elements.

**Comment by daKmoR** [comment]
you can use the mixing as described in the hybrid docs
https://www.polymer-project.org/2.0/docs/upgrade#mixins
